# Generated by Django 6.0.2 on 2026-02-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='template',
            name='created_by',
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
