# Generated by Django 6.0.2 on 2026-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_candidate_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='template',
        ),
        migrations.AddField(
            model_name='offerletter',
            name='candidate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='candidate_work_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
