# Generated by Django 6.0.2 on 2026-02-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offerletter_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='role',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('machine_learning', 'Machine Learning Engineer'), ('full_stack', 'Full Stack Developer'), ('ui_ux', 'UI/UX Designer'), ('digital_marketing', 'Digital Marketing'), ('pr', 'PR Specialist'), ('content', 'Content Writer'), ('video_editor', 'Video Editor')], help_text='Leave blank for general template', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
    ]
