# Generated by Django 6.0.2 on 2026-02-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_template_role_alter_offerletter_generated_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='offerletter',
            table='offer_letters',
        ),
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
    ]
