# Generated by Django 6.0.2 on 2026-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offerletter_options_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerletter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
        migrations.AlterModelTable(
            name='offerletter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='template',
            table=None,
        ),
    ]
