# Generated by Django 6.0.2 on 2026-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offerletter_options_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('machine_learning', 'Machine Learning Engineer'), ('full_stack', 'Full Stack Developer'), ('ui_ux', 'UI/UX Designer'), ('digital_marketing', 'Digital Marketing'), ('pr', 'PR Specialist'), ('content', 'Content Writer'), ('video_editor', 'Video Editor'), ('rnd', 'R&D Specialist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='role',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('machine_learning', 'Machine Learning Engineer'), ('full_stack', 'Full Stack Developer'), ('ui_ux', 'UI/UX Designer'), ('digital_marketing', 'Digital Marketing'), ('pr', 'PR Specialist'), ('content', 'Content Writer'), ('video_editor', 'Video Editor'), ('rnd', 'R&D Specialist')], help_text='Leave blank for general template', max_length=20, null=True),
        ),
        # Table rename removed - templates table already exists
    ]
