# Generated by Django 6.0.2 on 2026-02-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_candidate_role_alter_template_role_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
    ]
