# Generated by Django 4.2.7 on 2026-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_template_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='google_doc_id',
            field=models.CharField(blank=True, help_text='Google Doc ID for template', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, help_text='Local DOCX file (backup)', null=True, upload_to='templates/'),
        ),
    ]
