# Generated by Django 6.0.2 on 2026-02-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_template_role_alter_template_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('machine_learning', 'Machine Learning Engineer'), ('full_stack', 'Full Stack Developer'), ('ui_ux', 'UI/UX Designer'), ('digital_marketing', 'Digital Marketing'), ('pr', 'PR Specialist'), ('content', 'Content Writer'), ('video_editor', 'Video Editor'), ('rnd', 'R&D Specialist')], max_length=20),
        ),
    ]
